{% set name = "google-cloud-dns" %}
{% set version = "0.33.0" %}
{% set sha256 = "88f009333c5e7d18cb034b4651f8c0b35e5926f732054241d5008c7cc068f7a2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python >=3.6
    - google-cloud-core >=1.3.0,<3.0.0dev

test:
  imports:
    - google.cloud.client
    - google.cloud.dns

about:
  home: https://github.com/googleapis/python-dns
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud DNS API client library
  description: "Google Cloud DNS API provides methods that you can use to manage DNS for your applications. Google Cloud DNS is a scalable, reliable, and managed authoritative Domain Name System (DNS) service running on the same infrastructure as Google. It has low latency, high availability and is a cost-effective way to\
    \ make your applications and services available to your users. You can easily publish and manage millions of DNS zones and records using our API.\nSee the [quick start guide](https://googleapis.dev/python/dns/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dns/latest/index.html
  dev_url: https://github.com/googleapis/python-dns

extra:
  recipe-maintainers:
    - parthea
