{% set name = "google-cloud-dns" %}
{% set version = "0.35.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-dns-{{ version }}.tar.gz
  sha256: 0ac44da9eb0fa0b1229513cd888074abd0211992c4042300afd1c16d41474553

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-cloud-core >=1.4.4,<3.0dev

test:
  imports:
    - google.cloud.client
    - google.cloud.dns
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-dns
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud DNS API client library
  description: "Google Cloud DNS API provides methods that you can use to manage DNS for your applications. Google Cloud DNS is a scalable, reliable, and managed authoritative Domain Name System (DNS) service running on the same infrastructure as Google. It has low latency, high availability and is a cost-effective way to
    make your applications and services available to your users. You can easily publish and manage millions of DNS zones and records using our API.\nSee the [quick start guide](https://googleapis.dev/python/dns/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/dns/latest/index.html
  dev_url: https://github.com/googleapis/python-dns

extra:
  recipe-maintainers:
    - xylar
    - parthea
